version: '3.8'

services:
  db:
    image: postgres:16.5
    container_name: postgres-db
    environment:
      POSTGRES_DB: gosocial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  db-data:
