@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkX2F0IjoxNzI1OTMwNTA4LCJ1c2VyX2lkIjoiMSJ9._W3i66kDZVCWh4tKMvAUtPpGEhfEftCBoZDLQJ0e0JQ

### Register user
POST http://localhost:8080/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "email": "me@me.com",
  "password": "password",
  "first_name": "tiago",
  "last_name": "monta"
}

### Login user
POST http://localhost:8080/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "password": "password",
  "email": "me@me.com"
}

### Get all products
GET http://localhost:8080/api/v1/products HTTP/1.1
Accept: application/json

### Create product
POST http://localhost:8080/api/v1/products HTTP/1.1
Content-Type: application/json

{
  "name": "Macbook Pro 2022 M3",
  "description": "Macbook laptop with high performance",
  "image": "",
  "price": 2999.0,
  "quantity": 1000
}

### Create product
POST http://localhost:8080/api/v1/products HTTP/1.1
Content-Type: application/json

{
  "name": "Macbook Pro 2024 M4",
  "description": "Macbook laptop with high performance",
  "image": "",
  "price": 3999.0,
  "quantity": 1000
}

### Create order
POST http://localhost:8080/api/v1/cart/checkout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "items": [
    {
      "product_id": 44,
      "quantity": 2
    },
    {
      "product_id": 42,
      "quantity": 3
    }
  ]
}
