// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package products

import (
	"database/sql"
)

type Product struct {
	ID        int32
	Name      string
	Price     string
	Available sql.NullBool
	Created   sql.NullTime
}
